gcc aaindex.c -o aaindex  -lGLU -lGL -lglut
gcc aargb.c -o aargb  -lGLU -lGL -lglut
gcc accanti.c -o accanti  -lGLU -lGL -lglut
gcc accpersp.c -o accpersp  -lGLU -lGL -lglut
gcc alpha3D.c -o alpha3D  -lGLU -lGL -lglut
gcc alpha.c -o alpha  -lGLU -lGL -lglut
gcc bezcurve.c -o bezcurve  -lGLU -lGL -lglut
gcc bezmesh.c -o bezmesh  -lGLU -lGL -lglut
gcc bezsurf.c -o bezsurf  -lGLU -lGL -lglut
gcc blendeqn.c -o blendeqn  -lGLU -lGL -lglut
gcc checker.c -o checker  -lGLU -lGL -lglut
gcc clip.c -o clip  -lGLU -lGL -lglut
gcc colormat.c -o colormat  -lGLU -lGL -lglut
gcc colormatrix.c -o colormatrix  -lGLU -lGL -lglut
gcc colortable.c -o colortable  -lGLU -lGL -lglut
gcc combiner.c -o combiner  -lGLU -lGL -lglut
gcc convolution.c -o convolution  -lGLU -lGL -lglut
gcc cube.c -o cube  -lGLU -lGL -lglut
gcc cubemap.c -o cubemap  -lGLU -lGL -lglut
gcc dof.c -o dof  -lGLU -lGL -lglut
gcc double.c -o double  -lGLU -lGL -lglut
gcc drawf.c -o drawf  -lGLU -lGL -lglut
gcc feedback.c -o feedback  -lGLU -lGL -lglut
gcc fog.c -o fog  -lGLU -lGL -lglut
gcc fogcoord.c -o fogcoord  -lGLU -lGL -lglut
gcc fogindex.c -o fogindex  -lGLU -lGL -lglut
gcc font.c -o font  -lGLU -lGL -lglut
gcc hello.c -o hello  -lGLU -lGL -lglut
gcc histogram.c -o histogram  -lGLU -lGL -lglut
gcc image.c -o image  -lGLU -lGL -lglut
gcc light.c -o light  -lGLU -lGL -lglut
gcc lines.c -o lines  -lGLU -lGL -lglut
gcc list.c -o list  -lGLU -lGL -lglut
gcc material.c -o material  -lGLU -lGL -lglut
gcc minmax.c -o minmax  -lGLU -lGL -lglut
gcc mipmap.c -o mipmap  -lGLU -lGL -lglut
gcc model.c -o model  -lGLU -lGL -lglut
gcc movelight.c -o movelight  -lGLU -lGL -lglut
gcc multisamp.c -o multisamp  -lGLU -lGL -lglut
gcc multitex.c -o multitex  -lGLU -lGL -lglut
gcc mvarray.c -o mvarray  -lGLU -lGL -lglut
gcc pickdepth.c -o pickdepth  -lGLU -lGL -lglut
gcc picksquare.c -o picksquare  -lGLU -lGL -lglut
gcc planet.c -o planet  -lGLU -lGL -lglut
gcc pointp.c -o pointp  -lGLU -lGL -lglut
gcc polyoff.c -o polyoff  -lGLU -lGL -lglut
gcc polys.c -o polys  -lGLU -lGL -lglut
gcc quadric.c -o quadric  -lGLU -lGL -lglut
gcc readImage.c -o readImage  -lGLU -lGL -lglut
gcc robot.c -o robot  -lGLU -lGL -lglut
gcc scene.c -o scene  -lGLU -lGL -lglut
gcc select.c -o select  -lGLU -lGL -lglut
gcc shadowmap.c -o shadowmap  -lGLU -lGL -lglut
gcc smooth.c -o smooth  -lGLU -lGL -lglut
gcc stencil.c -o stencil  -lGLU -lGL -lglut
gcc stroke.c -o stroke  -lGLU -lGL -lglut
gcc surface.c -o surface  -lGLU -lGL -lglut
gcc surfpoints.c -o surfpoints  -lGLU -lGL -lglut
gcc teapots.c -o teapots  -lGLU -lGL -lglut
gcc tess.c -o tess  -lGLU -lGL -lglut
gcc tesswind.c -o tesswind  -lGLU -lGL -lglut
gcc texbind.c -o texbind  -lGLU -lGL -lglut
gcc texgen.c -o texgen  -lGLU -lGL -lglut
gcc texprox.c -o texprox  -lGLU -lGL -lglut
gcc texsub.c -o texsub  -lGLU -lGL -lglut
gcc texture3d.c -o texture3d  -lGLU -lGL -lglut
gcc texturesurf.c -o texturesurf  -lGLU -lGL -lglut
gcc torus.c -o torus  -lGLU -lGL -lglut
gcc trim.c -o trim  -lGLU -lGL -lglut
gcc unproject.c -o unproject  -lGLU -lGL -lglut
gcc varray.c -o varray  -lGLU -lGL -lglut
gcc wrap.c -o wrap  -lGLU -lGL -lglut
